# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u95ee\u9898\u8868', 'verbose_name_plural': '\u95ee\u9898\u8868'},
        ),
    ]
