# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-17 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch01', '0003_auto_20190117_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='job',
        ),
        migrations.DeleteModel(
            name='SalGrade',
        ),
        migrations.DeleteModel(
            name='Dep',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
