# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-08 11:23
from __future__ import unicode_literals

import ch05.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch05', '0002_auto_20190107_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=ch05.models.get_file_path),
        ),
    ]
