# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch05', '0010_auto_20190108_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='ch05.Hobby'),
        ),
    ]
