# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch05', '0013_auto_20190108_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237\u8868', 'verbose_name_plural': '\u7528\u6237\u8868'},
        ),
    ]
