# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-01 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0003_auto_20181201_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='\u5de5\u8d44'),
        ),
    ]
