# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0004_person_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=128)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('commission_pct', models.FloatField(null=True)),
                ('manager_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
