# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0005_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Emp',
        ),
    ]
