# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0006_auto_20181202_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('level', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='emp',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ch03.Dep'),
        ),
        migrations.AddField(
            model_name='emp',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ch03.Job'),
        ),
    ]
