# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-11 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0010_author_blog_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tagline',
            new_name='keywords',
        ),
    ]
