# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch03', '0014_auto_20190111_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch03.Blog'),
        ),
    ]
